server:
  port: 3002

spring:
  ai:
    dashscope:
      api-key: ${DASHSCOPE_API_KEY:sk-4e208c79817945e9b2f62217a82a17ff}
      chat:
        options:
          model: deepseek-r1

# 大模型配置
lmm:
  max-retry-count: 3  # 模型结果不符合要求时的最大重试次数
  timeout: 4000       # 单次请求超时时间(毫秒)