server:
  port: 3002

spring:
  ai:
    dashscope:
      chat:
        options:
          model: deepseek-r1-0528
  profiles:
    include: secrets

logging:
  level:
    org.springframework.ai.chat.client.advisor: debug
    com.gamehive.lmmrunningsystem: debug
# 大模型配置
lmm:
  max-retry-count: 3  # 模型结果不符合要求时的最大重试次数
  timeout: 200000       # 单次请求超时时间(毫秒)-200秒