server:
  port: 3002

spring:
  ai:
    dashscope:
      chat:
        options:
          model: deepseek-r1
  profiles:
    include: secrets

# 大模型配置
lmm:
  max-retry-count: 3  # 模型结果不符合要求时的最大重试次数
  timeout: 4000       # 单次请求超时时间(毫秒)