server:
  port: 3002

spring:
  ai:
    dashscope:
      chat:
        options:
          model: deepseek-r1-distill-llama-8b
  profiles:
    include: secrets
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

springfox:
  documentation:
    enabled: false

logging:
  level:
    org.springframework.ai.chat.client.advisor: debug
    com.gamehive.lmmrunningsystem: debug

# 大模型配置
lmm:
  max-retry-count: 3    # 模型结果不符合要求时的最大重试次数
  
# URL配置
api:
  urls:
    receive-bot-move: "http://127.0.0.1:3000/api/pk/receive/LMM/move/"